public/icon/delete.svg, public/icon/more-options.svg
<br/>
<br/>
- 커뮤니티 상세페이지 및 댓글에서 사용하는 아이콘을 추가.
<br/>
<br/>
<br/>
=> [style] community icon #38

prisma/migrations/20250221010855_add_community_post_status/migration.sql, prisma/schema.prisma
<br/>
<br/>
- 커뮤니티 게시글 테이블에 상태를 추가
- 기본상태는 `recruiting` - 모집중
- `completed` - 모집완료
<br/>
<br/>
<br/>
=> [database] 커뮤니티 게시글 상태 추가 #40

components/dropdown/Dropdown.styled.tsx, components/dropdown/Dropdown.tsx, package-lock.json, package.json
<br/>
드롭다운 컴포넌트 생성
<br/>
<br/>
실제 db와 연동해서 options에 넣고 selected api에 보내기 
<br/>
- [fungle #42 ]
<br/>
=> [feat] 02/21 드롭다운 컴포넌트 생성 #42

prisma/migrations/20250221024218_add_community_post_community_recruitment_field/migration.sql, prisma/schema.prisma
<br/>
<br/>
- 커뮤니티 게시글 작성 테이블에서 기존 장르 테이블을 제거하고 모집 분야 테이블로 변경함.
<br/>
<br/>
<br/>
=> [database] 02/21 커뮤니티 게시글 모집 분야 테이블 추가 및 커뮤니티 게시글 장르 테이블 삭제 #44

components/textarea/Textarea.styled.tsx, components/textarea/Textarea.tsx
<br/>
```
<Textarea
placeholder={placeholder}
width={width}
height={height}
/>
```
- placeholder(필수): 필요한 내용 입력
- width(선택): 입력 안 할 시 100% 적용, 필요한 수치로 변경 가능
- height(선택): 입력 안 할 시 10rem 적용, 필요한 수치로 변경 가능
<br/>
<br/>
<br/>
- [fungle #47 ]
<br/>
=> [feat] textarea 컴포넌트 구현 #47

app/globals.css, constants/COMMUNITY_POST_LIST.ts, constants/GENRES.ts, constants/RECRUITMENT_FIELDS.ts
<br/>
<br/>
```ts
// 커뮤니티 게시글 작성 모집 분야 옵션
export const RECRUITMENT_FIELDS = [
{ value: "writer", label: "작가" },
{ value: "designer", label: "디자이너" },
{ value: "editor", label: "편집자" },
{ value: "planner", label: "기획자" },
];
```
```ts
// 소설 장르 옵션
export const GENRES = [
{ value: "romance", label: "로맨스" },
{ value: "horror_thriller", label: "공포/스릴러" },
{ value: "fantasy", label: "판타지" },
{ value: "action", label: "액션" },
{ value: "daily_life", label: "일상" },
{ value: "comedy", label: "개그" },
{ value: "martial_arts", label: "무협/사극" },
{ value: "game_fantasy", label: "게임판타지" },
{ value: "art", label: "예술" },
{ value: "sports", label: "스포츠" },
{ value: "growth", label: "성장물" },
];
```
```ts
// 커뮤니티 게시글 목록 조회 옵션
export const COMMUNITY_POST = [
{ value: "title", label: "제목" },
{ value: "author", …
```
=> [chore] filter option #52

components/dropdown/Dropdown.tsx
<br/>
<br/>
``` tsx
"use client";
import { useState } from "react";
import Dropdown from "@/components/dropdown/Dropdown";
import { COMMUNITY_POST_LIST } from "@/constants/COMMUNITY_POST_LIST"; 
const ExampleComponent = () => {
const [selected, setSelected] = useState(COMMUNITY_POST_LIST[0].value); 
return (
<div>
<h2>정렬 기준: {selected}</h2>
<Dropdown 
options={COMMUNITY_POST_LIST} 
onSelect={setSelected} 
selected={selected} 
size="default" 
/>
</div>
);
};
export default ExampleComponent;
```
<br/>
<br/>
- [fungle #53 ]
<br/>
=> [fix] 02/21 dropdown 수정 #53

components/input/Input.styled.tsx, components/input/Input.tsx
<br/>
```
<Input size="small" hideLabel={true} />
```
- size: big(default, 335px), medium(245px), small(100px)
- hideLabel: false(default), true(label 숨겨짐)
<br/>
<br/>
<br/>
- [fungle #57 ]
<br/>
=> [fix] input 사이즈 props로 변경

components/dropdown/Dropdown.styled.tsx, components/sidebar/Sidebar.styled.tsx, components/sidebar/Sidebar.tsx
<br/>
<br/>
<br/>
<br/>
- [프로젝트명 #53 ]
<br/>
=> [fix] dropdown animation 변경 및 dropdown bordercolor 변경 #53

app/admin/community/page.styled.tsx, components/dropdown/Dropdown.styled.tsx, components/input/Input.styled.tsx
<br/>
input, dropdown 컴포넌트 폭 기본값 100%로 변경
<br/>
<br/>
<br/>
- [fungle #70 ]
<br/>
=> [fix] input, dropdown 폭 기본값 변경

components/textarea/Textarea.styled.tsx, components/textarea/Textarea.tsx
<br/>
```
<Textarea placeholder={placeholder} width={width} height={height}
defaultValue={defaultValue} ariaLabel={ariaLabel} />
```
- placeholder, width, height, defaultValue: optional
- ariaLabel: 필수, 사용 방법 작성(e.g. 소설을 작성하는 부분)
<br/>
<br/>
<br/>
- [fungle #64 ]
<br/>
=> [fix] textarea 수정

app/globals.css, app/user/community/create/CommunityPostCreatePage.styled.tsx, app/user/community/create/page.tsx, next.config.ts
<br/>
<br/>
- 커뮤니티 게시글 작성 페이지 UI 작업
- RootLayout flex추가
- styled-components 설정
<br/>
<br/>
- [fungle #55 ]
<br/>
=> [design] community post create #55

app/user/community/create/page.tsx
<br/>
<br/>
- 커뮤니티 게시글 작성 페이지 Textarea 내용 수정
<br/>
<br/>
- [fungle #74 ]
<br/>
=> [design] 게시글 작성 textarea 내용 수정 #74

components/input/Input.tsx
<br/>
```
<Input placeholder={placeholder} src={src} $size={$size} aria-label={label} {...props} />
```
- name, type과 같은 기본 input 속성을 전달받을 수 있도록 변경
<br/>
<br/>
login 페이지 input 수정
<br/>
- [fungle #80 ]
<br/>
=> [fix] input component 수정 #80

components/button/Button.styled.tsx, components/button/Button.tsx, components/input/Input.styled.tsx, components/input/Input.tsx
<br/>
- input 컴포넌트 iconPosition prop 추가
- input 컴포넌트 width 삭제
- button 컴포넌트 padding 삭제
- button 컴포넌트 width big, medium, small로 전달
<br/>
<br/>
<br/>
- [fungle #83 ]
<br/>
=> [fix] input, button 컴포넌트 수정 #83

app/user/community/CommunityList.styled.tsx, app/user/community/components/CommunityListFilter.styled.tsx, app/user/community/components/CommunityListFilter.tsx, app/user/community/components/CommunityPagination.styled.tsx, app/user/community/components/CommunityPagination.tsx, app/user/community/components/CommunityPostList.styled.tsx, app/user/community/components/CommunityPostList.tsx, app/user/community/components/CommunitySearchFilter.styled.tsx, app/user/community/components/CommunitySearchFilter.tsx, app/user/community/page.tsx, app/user/community/utils/getPostStats.ts
<br/>
<br/>
- 커뮤니티 게시글 페이지 UI 작업
<br/>
https://github.com/user-attachments/assets/3379392f-5a17-43a5-a5eb-95f3adc807fa
- DB에서 데이터를 가져와 연동하기
<br/>
- [fungle #73 ]
<br/>
=> [design] 커뮤니티 게시글 리스트 페이지 UI 작업

prisma/migrations/20250223122648_add_title_nullable/migration.sql, prisma/migrations/20250223122830_make_title_required/migration.sql, prisma/schema.prisma
<br/>
database values 입력 및 episode에 title column 추가
<br/>
<br/>
<br/>
- [fungle #78]
<br/>
=> [database] 02/23 database values 입력 및 episode에 title column 추가 #78

application/usecases/novel/DfNovelUsecase.ts, application/usecases/novel/dto/Novel.ts
<br/>
<br/>
<br/>
<br/>
- [fungle #93 ]
<br/>
=> [hotfix] 02/23 application 폴더 추가 #93

application/usecases/user/dto/User.ts, domain/entities/user.ts
<br/>
<br/>
<br/>
<br/>
- [fungle #96 ]
<br/>
=> [feat] 02/24 user entity dto 추가 #96

app/(anon)/login/LoginPage.styled.tsx, app/(anon)/login/page.tsx, components/button/Button.styled.tsx, components/dropdown/Dropdown.styled.tsx, components/input/Input.styled.tsx
<br/>
- 컴포넌트 글자 크기 변경(placeholder로 통일)
<br/>
<br/>
<br/>
- [fungle #97 ]
<br/>
=> [design] input, dropdown, button 컴포넌트 글자 크기 변경 #97

app/globals.css
<br/>
<br/>
<br/>
<br/>
- [fungle #100 ]
<br/>
=> [design] 02/24 global css 수정 #100

app/globals.css, components/header/Header.styled.tsx
<br/>
<br/>
<br/>
<br/>
- [fungle #100 ]
<br/>
=> [design] global css, header 변경 #100

app/(anon)/signup/Signup.styled.tsx, app/(anon)/signup/page.tsx, components/button/Button.styled.tsx
<br/>
회원가입 UI 작성
잘못 작성했을시 경고문 띄우기
<br/>
<br/>
- 실제 로그인 동작 수행하기
- 데이터베이스 연결하기
<br/>
- [fungle #62 ]
<br/>
=> Design/62 회원가입 페이지 UI

prisma/schema.prisma
… 위한 중간 테이블 communityPostRecruitment 생성
<br/>
-  `communityPost` 테이블과 `communityRecruitmentField` 테이블 다대다 관계를 위해 중간 테이블 `communityPostRecruitment` 테이블 추가
<br/>
<br/>
<br/>
- [fungle #112 ]
<br/>
=> [database] communityPost 테이블 관계 설정

prisma/schema.prisma
<br/>
- 테이블명을 카멜케이스에서 파스칼 케이스로 변경 
- 변수명이랑 헷갈릴 우려가 있어 파스칼로 변경
<br/>
<br/>
<br/>
- [fungle #118 ]
<br/>
=> [database] 테이블명 파스칼케이스로 변경 #118

app/(anon)/signup/page.tsx, app/api/signup/route.ts, application/usecases/auth/DfCheckEmailDuplicationUsecase.ts, application/usecases/auth/DfCheckNicknameDuplicationUsecase.ts, application/usecases/auth/DfHashPasswordUsecase.ts, application/usecases/auth/DfRegisterUsecase.ts, application/usecases/auth/dto/CheckEmailDto.ts, application/usecases/auth/dto/CheckNicknameDto.ts, application/usecases/auth/dto/HashPasswordDto.ts, application/usecases/auth/dto/RegisterUserDto.ts, domain/repositories/AuthRepository.ts, infrastructure/repositories/PrAuthRepository.ts
<br/>
- 회원가입 DTO, 유스케이스 구성
- API, 라우터 구성 
<br/>
<br/>
- 이메일 인증 구현 
<br/>
- [Fungle #84]
<br/>
=> [feat] 회원가입 기능 기본 구조 구현

components/input/Input.styled.tsx, components/input/Input.tsx
<br/>
<br/>
<br/>
input에 더이상 수정사항이 없도록 기도하기
<br/>
- [fungle #115 ]
<br/>
=> [design] input container position 추가, aria-label 삭제 #115

app/user/novel/[novelId]/page.tsx, application/usecases/novel/DfNovelUsecase.ts, application/usecases/novel/dto/Novel.ts, domain/entities/novel.ts, domain/repositories/NovelRepository.ts, infrastructure/config/novelDi.ts, infrastructure/repositories/PrNovelRepostiory.ts
<br/>
<br/>
<br/>
<br/>
- [fungle #117 ]
<br/>
=> [refactor] 02/25 novel 클린아키텍처 준수 #117

prisma/schema.prisma
<br/>
- User 테이블에 profileImage 추가
- 모집 분야 테이블명 수정
<br/>
<br/>
<br/>
- [fungle #130 ]
<br/>
=> [database]  데이터 베이스 유저, 커뮤니티 모집분야 테이블 수정 #130

app/user/novel/[novelId]/(episode)/[episodeId]/EpisodePage.styled.tsx, app/user/novel/[novelId]/(episode)/[episodeId]/page.tsx
<br/>
<br/>
<br/>
BE 연결
<br/>
- [fungle #108 ]
<br/>
=> [design] 02/25 episode UI #108

app/user/novel/[novelId]/(episode)/[episodeId]/EpisodePage.styled.tsx, app/user/novel/[novelId]/(episode)/[episodeId]/page.tsx, application/usecases/novel/DfEpisodeByIdUseCase.ts, application/usecases/novel/DfEpisodesByNovelIdUseCase.ts, application/usecases/novel/dto/NovelEpisodeDto.ts, domain/repositories/NovelEpisodeRepository.ts, infrastructure/config/novelDi.ts, infrastructure/repositories/PrNovelEpisodeRepository.ts
<br/>
<br/>
<br/>
<br/>
- [fungle #133 ]
<br/>
=> [feat] 02/25 episode db 연결 #133

app/user/novel/[novelId]/(episode)/[episodeId]/page.tsx, components/novelcompleted/NovelCompleted.styled.tsx, components/novelcompleted/NovelCompleted.tsx
<br/>
<br/>
<br/>
DB에서 novel status를 가져와서 novel status가 completed이면 episode의 마지막 화에서 컴포넌트 표시
<br/>
- [fungle #134 ]
<br/>
=> [design] 02/26 novel 완결 펀딩 연결 컴포넌트 #134

infrastructure/config/disconnect.js, infrastructure/config/prisma.ts, infrastructure/config/terminate.js, tsconfig.json
<br/>
<br/>
<br/>
<br/>
- [fungle #142 ]
<br/>
=> hotfix/ 02/26 prisma connect 해결 #142

app/api/login/route.ts, application/usecases/auth/DfLoginUsecase.ts, application/usecases/auth/DfSetAuthCookieUsecase.ts, application/usecases/auth/dto/LoginResponseDto.ts, application/usecases/auth/interfaces/ISetAuthCookieUsecase.ts, domain/repositories/AuthRepository.ts, infrastructure/repositories/PrAuthRepository.ts, package-lock.json, package.json, prisma/schema.prisma, utils/auth/jwt.ts
<br/>
- 로그인 시 토큰 db에 저장
- 쿠키에 refresh token 저장
<br/>
<br/>
<br/>
- [fungle #123 ]
<br/>
=> [feat] 토큰 발급 및 db에 저장 #123

app/user/novel/[novelId]/(episode)/[episodeId]/page.tsx, app/user/novel/[novelId]/NovelIdPage.styled.tsx, app/user/novel/[novelId]/page.tsx, application/usecases/novel/DfNovelUsecase.ts, application/usecases/novel/dto/Novel.ts, domain/repositories/NoveLikeRepository.ts, domain/repositories/NovelGenreRepository.ts, domain/repositories/NovelRepository.ts, domain/repositories/UserRepository.ts, infrastructure/config/novelDi.ts, infrastructure/repositories/PrNovelGenreRepository.ts, infrastructure/repositories/PrNovelLikeRepository.ts, infrastructure/repositories/PrNovelRepostiory.ts, infrastructure/repositories/PrUserRepository.ts
<br/>
<br/>
<br/>
<br/>
- [fungle #117 ]
<br/>
=> [refactor] novel Repository 테이블별 분리 #117

app/api/auth/refresh/route.ts, application/usecases/auth/DfRefreshTokenUsecase.ts, application/usecases/auth/DfVerifyAccessToken.ts, application/usecases/auth/interfaces/IRefreshTokenUsecase.ts, domain/repositories/AuthRepository.ts, infrastructure/repositories/PrAuthRepository.ts, utils/auth/jwt.ts
<br/>
토큰 갱신 함수 구현(테스트는 아직)
<br/>
<br/>
<br/>
- [fungle #152 ]
<br/>
=> [feat] 토큰 갱신 함수 구현 #152

app/user/community/components/CommunitySearchFilter.tsx, constants/COMMUNITY_POST_LIST.ts
<br/>
- 커뮤니티 리스트 정렬 상수를 분리 하였습니다.
- onSearch 타입을 변경하였습니다.
<br/>
<br/>
<br/>
- [fungle #162 ]
<br/>
=> [refactor] 커뮤니티 리스트 정렬 상수 분리 #162

prisma/schema.prisma
<br/>
- RefreshToken id default 변경 -> uuid
<br/>
<br/>
<br/>
- [fungle #165 ]
<br/>
=> [database] RefreshToken id default 변경 #165

app/api/auth/verify/route.ts, app/layout.tsx, context/AuthContext.tsx, hooks/useAuth.ts
<br/>
- 페이지에서 로그인 상태 확인할 수 있는 useAuth 훅
- 로그인 상태를 전역적으로 관리하는 AuthContext
<br/>
<br/>
- 마이페이지 UI 구현
<br/>
- [fungle #154 ]
<br/>
=> [feat] 로그인 상태 전역 관리 #154

app/(anon)/signup/Signup.styled.tsx, app/(anon)/signup/page.tsx
<br/>
- 인증코드 확인하기 버튼 ui 추가
<br/>
<br/>
- 인증코드 확인하는 기능 추가
<br/>
=> [feat] 02/28 인증코드 확인 버튼 추가하기

app/user/novel/create/component/NovelCreateCompleted.tsx, app/user/novel/create/component/NovelCreatedCompleted.styled.tsx, app/user/novel/create/page.tsx, app/user/novel/page.tsx, app/user/novel/serialize/SerializePage.styled.tsx, app/user/novel/serialize/[novelId]/page.tsx, prisma/schema.prisma
<br/>
<br/>
https://github.com/user-attachments/assets/bf166912-0489-4ea6-9ef9-5904dc7d054a
<br/>
BE 연결
<br/>
- [fungle #164 ]
<br/>
=> Design/164 serialize UI

app/user/novel/create/page.tsx
<br/>
<br/>
<br/>
<br/>
- [fungle #164 ]
<br/>
=> [design] 02/28 소설 연재push router 수정 #164

app/user/novel/page.tsx
=> [design] 02/28 로그인 시 500번 에러를 없애기 위한 소설 메인페이지 #182

app/(anon)/signup/components/EmailVerification.tsx, app/(anon)/signup/components/NicknameValidation.tsx, app/(anon)/signup/components/PasswordFields.tsx, app/(anon)/signup/components/SignupButton.tsx, app/(anon)/signup/page.tsx
<br/>
- 회원가입 컴포넌트 분리
<br/>
<br/>
- 이메일 인증하기 연결하기
- 회원가입시 유저 정보 DB에 저장되기
<br/>
- [fungle #176 ]
<br/>
=> [feat] 02/28 회원가입 컴포넌트 분리

app/api/auth/verify/route.ts, application/usecases/auth/DfVerifyRefreshToken.ts, utils/auth/jwt.ts
<br/>
```
const user = useAuth();
```
필요한 페이지에서 useAuth 훅 사용하면 userId 가져올 수 있습니다.
<br/>
<br/>
<br/>
- [fungle #185 ]
<br/>
=> [feat] refreshToken으로 사용자 정보 가져오기 #185

app/(anon)/signup/components/EmailVerification.tsx
<br/>
- 버튼 누를시 이메일 인증하기 
<br/>
<br/>
- 이메일 인증하기 기능 구현
- 회원가입 기능 구현
<br/>
- [fungle #175 ]
<br/>
=> [feat] 02/28 버튼 누를시 이메일 인증

app/api/community/create/route.ts, app/user/community/components/CommunityListFilter.tsx, app/user/community/components/CommunityPostForm.tsx, app/user/community/components/CommunityPostList.tsx, app/user/community/create/page.tsx, application/usecases/community/DfPostCreateUsecase.ts, application/usecases/community/dto/PostCreateDto.ts, domain/repositories/CommunityPostRepository.ts, infrastructure/repositories/PrCommunityPostRepository.ts, prisma/schema.prisma
<br/>
- 커뮤니티 게시글 작성 기능 구현
- 커뮤니티 작성 완료 시 해당 게시글 상세페이지로 이동
<br/>
https://github.com/user-attachments/assets/9706dc39-6670-41d8-8907-0c88f54a1ff5
<br/>
<br/>
- [fungle #27 ]
<br/>
=> [feat] 커뮤니티 게시글 작성 기능 구현 #27

app/api/user/nickname/route.ts, app/user/components/ProfileView.styled.tsx, app/user/components/ProfileView.tsx, application/usecases/user/DfUpdateNicknameUsecase.ts, application/usecases/user/error/NicknameError.ts, domain/repositories/UserRepository.ts, infrastructure/repositories/PrUserRepository.ts
<br/>
닉네임 변경 api를 구현/연결했습니다.
<br/>
<br/>
- 작가 소개 생성/수정 api 구현
<br/>
- [fungle #198 ]
<br/>
=> [feat] 닉네임 수정 api 구현

app/api/community/[id]/comments/route.ts, app/api/community/[id]/route.ts, app/api/community/[id]/update/route.ts, app/api/community/create/route.ts, application/usecases/community/DfPostDetailCommentUsecase.ts, application/usecases/community/DfPostDetailUsecase.ts, domain/repositories/CommunityCommentRepository.ts, domain/repositories/CommunityPostRepository.ts, infrastructure/repositories/PrCommunityCommentRepository.ts, infrastructure/repositories/PrCommunityPostRepository.ts
<br/>
- 커뮤니티 api/route 단에서 params 타입 변경 및 await 추가
- userId id로 불러온 후 userId로 변경
<br/>
<br/>
<br/>
<br/>
=> [refactor]  커뮤니티 api/route refactor #205

app/api/novel/[novelId]/[episodeId]/route.ts, app/api/novel/[novelId]/route.ts, infrastructure/repositories/PrNovelEpisodeRepository.ts
<br/>
<br/>
<br/>
<br/>
- [fungle #207 ]
<br/>
=> [fix] novel approved 만 보여주기

app/api/novel/[novelId]/[episodeId]/route.ts, app/user/novel/[novelId]/(episode)/[episodeId]/page.tsx, application/usecases/novel/DfIncreaseViewCountUsecase.ts, application/usecases/novel/dto/NovelEpisode.ts, domain/repositories/NovelEpisodeRepository.ts, infrastructure/config/novelDi.ts, infrastructure/repositories/PrNovelEpisodeRepository.ts
<br/>
새로고침 할 때마다 조회수 추가
<br/>
<br/>
<br/>
- [fungle #214 ]
<br/>
=> [feat]  소설 조회수 

app/user/novel/[novelId]/(episode)/[episodeId]/EpisodePage.styled.tsx, app/user/novel/[novelId]/NovelIdPage.styled.tsx, app/user/novel/[novelId]/page.tsx
<br/>
<br/>
<br/>
<br/>
- [fungle #218 ]
<br/>
=> [design] novel page 사진 찌그러짐 수정

app/api/auth/register/route.ts, application/usecases/auth/DfSignupUsecase.ts
<br/>
- 회원가입 정보 라우터 연결
- 회원가입 정보 프리스마 테이블에 저장
- 
<br/>
<br/>
레이아웃 개선 및 이메일 파일 개선
<br/>
- [fungle #202 ]
<br/>
=> [feat] 라우터 연결

app/(anon)/signup/Signup.styled.tsx, app/(anon)/signup/components/EmailVerification.tsx
<br/>
- 레이아웃 개선
- 버튼 아래에 깔리는 현상 수정
- 이메일 verification 수정 
<br/>
<br/>
- 펀딩 페이지 작업하기
<br/>
- [fungle #222 ]
<br/>
=> [feat] 회원가입 페이지 UI 개선 #222

components/button/Button.styled.tsx, components/button/Button.tsx, components/textarea/Textarea.tsx
<br/>
- 버튼에 success 색상 추가
- textarea 컴포넌트 label 삭제
<br/>
<br/>
- 컴포넌트 수정 사항이 없도록 기도하기
<br/>
- [fungle #231 ]
<br/>
=> [feat] 버튼과 textarea 컴포넌트 수정

app/api/user/novel/route.ts, app/user/components/ProfileNovelList.styled.tsx, app/user/components/ProfileNovelList.tsx, application/usecases/novel/DfEpisodeByUserIdUsecase.ts, application/usecases/novel/DfNovelByUserIdUsecase.ts, application/usecases/novel/dto/NovelEpisodesByUserId.ts, application/usecases/novel/dto/NovelsByUserId.ts, constants/EPISODE_STATUS.ts, domain/repositories/NovelEpisodeRepository.ts, domain/repositories/NovelRepository.ts, infrastructure/repositories/PrNovelEpisodeRepository.ts, infrastructure/repositories/PrNovelRepostiory.ts
<br/>
- userId를 사용해 소설, 에피소드 조회를 구현했습니다.
<br/>
<br/>
<br/>
- [fungle #229 ]
<br/>
=> [feat] userId로 소설, 에피소드 조회 구현 #229

app/(anon)/novel/page.tsx
<br/>
<br/>
<br/>
<br/>
- [fungle #182 ]
<br/>
=> [design] 03/05 anon novel page 생성 #182

app/api/novel/like/route.ts, app/user/novel/[novelId]/page.tsx, app/user/novel/component/NovelLikeButton.styled.tsx, app/user/novel/component/NovelLikeButton.tsx, application/usecases/novel/DfToggleNovelLikeUsecase.ts, application/usecases/novel/dto/ToggleNovelLike.ts, domain/repositories/NoveLikeRepository.ts, infrastructure/repositories/PrNovelLikeRepository.ts
<br/>
<br/>
<br/>
<br/>
- [fungle #239 ]
<br/>
=> [feat]  novel 좋아요 

app/api/user/nickname/route.ts, app/api/user/novel/route.ts, app/api/user/profile-image/route.ts, application/usecases/auth/DfGetUserIdUsecase.ts, infrastructure/config/userDi.ts
<br/>
route에서 `const userId = await userDi.getUserIdUsecase.execute(req);` 사용
<br/>
<br/>
<br/>
- [fungle #242 ]
<br/>
=> [feat] 사용자 아이디 가져오는 usecase 구현 #242

prisma/schema.prisma
<br/>
- NovelEpisode 테이블에 에피소드 완결 상태를 나타내는 컬럼 추가
<br/>
<br/>
<br/>
- [fungle #247 ]
<br/>
=> [database] NovelEpisode 테이블 isFinalEpisode 컬럼 추가 #247

app/api/user/community/route.ts, app/api/user/introduce/route.ts, app/api/user/nickname/route.ts, app/api/user/profile-image/route.ts, app/user/MyPage.styled.tsx, app/user/components/PostAndLikedListWrapper.styled.tsx, app/user/components/ProfileIntroduce.tsx, app/user/components/ProfilePostList.tsx, app/user/components/ProfileView.tsx, application/usecases/community/DfPostDetailByUserIdUsecase.ts, application/usecases/community/DfPostStatusUpdateUsecase.ts, application/usecases/community/dto/PostWithRecruitmentDto.ts, domain/repositories/CommunityPostRepository.ts, infrastructure/repositories/PrCommunityPostRepository.ts
<br/>
- userId로 커뮤니티 게시글 조회
- 게시글 모집 상태 변경
<br/>
<br/>
<br/>
- [fungle #221 ]
<br/>
=> [feat] 마이페이지 커뮤니티 게시글 조회 및 모집 상태 변경 api 구현 #221

app/api/novel/serial-day/[day]/route.ts, app/user/novel/component/MyBook.styled.tsx, app/user/novel/component/MyBook.tsx, app/user/novel/component/SerialDayBook.styled.tsx, app/user/novel/component/SerialDayBook.tsx, application/usecases/novel/DfNovelsBySerialDayUsecase.ts, application/usecases/novel/dto/SerialDayNovel.ts, domain/repositories/NovelRepository.ts, infrastructure/config/novelDi.ts, infrastructure/repositories/PrNovelRepostiory.ts
<br/>
<br/>
https://github.com/user-attachments/assets/c4a11a24-0bdd-4017-8ba5-6c943a8a5c48
<br/>
<br/>
- [fungle #252 ]
<br/>
=> [feat] 소설 메인페이지 요일 별 연재

app/api/community/comment/[id]/route.ts, application/usecases/comment/DfCommentDeleteUseccase.ts, components/comment/Comment.tsx, domain/repositories/CommunityCommentRepository.ts, infrastructure/repositories/PrCommunityCommentRepository.ts
<br/>
- 커뮤니티 댓글 삭제 기능 구현
<br/>
https://github.com/user-attachments/assets/7443a759-3e04-477c-8ae8-017d1e6d0ba6
<br/>
- 댓글 좋아요 기능 구현
<br/>
- [fungle #29 ]
<br/>
=> [feat] 커뮤니티 댓글 삭제 기능 구현 #29 

styles/email/sendEmailTemplate.tsx
<br/>
- 로고 수정
- 텍스트 수정
<br/>
<br/>
펀딩 UI 작업
<br/>
- [fungle #256 ]
<br/>
=> [design] 03/06 이메일 형식 수정

app/(anon)/login/actions/loginProc.ts, app/api/auth/verify/route.ts, app/api/community/[id]/route.ts, app/api/community/[id]/update/route.ts, app/api/community/comment/[id]/route.ts, app/api/community/create/route.ts, app/api/community/like/route.ts, app/api/novel/like/route.ts, app/api/user/community/route.ts, app/api/user/introduce/route.ts, app/api/user/nickname/route.ts, app/api/user/novel/route.ts, app/api/user/profile-image/route.ts, app/user/components/ProfileIntroduce.tsx, app/user/components/ProfileNovelList.tsx, app/user/components/ProfilePostList.tsx, app/user/components/ProfileView.tsx, app/user/novel/component/NovelLikeButton.tsx, app/user/novel/create/page.tsx, application/usecases/auth/DfGetUserIdUsecase.ts, application/usecases/auth/DfRefreshTokenUsecase.ts, application/usecases/auth/DfVerifyAccessToken.ts, infrastructure/config/novelDi.ts, infrastructure/config/userDi.ts, middleware.ts, store/useAuthStore.ts, utils/auth/jwt.ts
<br/>
- userId 조회 로직 최종 변경
<br/>
<br/>
더는 변경되지 않도록 기도하기
<br/>
- [fungle #250 ]
<br/>
=> [fix] 토큰 용도 수정  #250

app/api/novel/banner/route.ts, app/user/novel/component/BannerCarousel.tsx, app/user/novel/component/BannerCorousel.styled.tsx, application/usecases/novel/DfBannerNovelsUsecase.ts, application/usecases/novel/dto/Banner.ts, domain/repositories/NovelRepository.ts, infrastructure/config/novelDi.ts, infrastructure/repositories/PrNovelRepostiory.ts
<br/>
<br/>
<br/>
<br/>
- [ fungle #258 ]
<br/>
=> [feat] banner DB 연결 

app/api/community/[id]/comments/route.ts, app/api/community/comment/[id]/like/route.ts, application/usecases/comment/DfToggleCommentUsecase.ts, application/usecases/community/DfPostDetailCommentUsecase.ts, application/usecases/community/dto/PostDetailCommentsWithUserDto.ts, components/comment/Comment.tsx, domain/repositories/CommunityCommentLikeRepository.ts, domain/repositories/CommunityCommentRepository.ts, infrastructure/repositories/PrCommunityCommentLikeRepository.ts, infrastructure/repositories/PrCommunityCommentRepository.ts
<br/>
- 댓글 좋아요 기능 구현 
- 로그인한 사용자가 좋아요를 누를 시 이미지 UI 변경
<br/>
https://github.com/user-attachments/assets/ef57fea5-9fcb-4384-a5b9-6bb4121b39dc
<br/>
- 게시글 조회수 기능 구현
<br/>
- [fungle #31 ]
<br/>
=> [feat]  댓글 좋아요 기능 구현 #31

app/api/community/[id]/comments/route.ts, app/api/community/comment/[id]/like/route.ts
<br/>
- userId를 불러오는 방식을 변경 
```tsx
const userId = await userDi.getUserIdUsecase.execute();
if (!userId) {
return NextResponse.json(
{ error: "유효하지 않은 사용자" },
{ status: 401 }
);
}
```
<br/>
<br/>
<br/>
<br/>
=> [refactor] 03/06 userId를 userDi.getUserIdUsecase.execute 불러오는 방식으로 변경

app/user/novel/component/MyBook.styled.tsx
<br/>
<br/>
<br/>
<br/>
- [fungle #264 ]
<br/>
=> [design] 03/07 소설 메인페이지 글자 wrap , 썸네일 크기 고정 #264

prisma/schema.prisma
<br/>
- Funding 테이블 title 컬럼 -> introduce 로 변경
- status 컬럼  @default("pending") ->@default("ongoing") 로 변경
<br/>
<br/>
<br/>
- [fungle #270 ]
<br/>
=> [database] 03/07 Funding 테이블 title -> introduce 변경 #270

prisma/schema.prisma
<br/>
- Funding 테이블 currentAmount  @default(0) 값 설정
- FundingStage 테이블 stageNumber  @default(1) 값 설정
<br/>
<br/>
<br/>
- [fungle #275 ]
<br/>
=> [database] 03/07 Funding 테이블 수정 #275

app/user/components/LikedNovelList.tsx, app/user/components/LikedPostList.tsx, app/user/components/PostAndLikedListWrapper.styled.tsx, app/user/components/ProfileLikedList.tsx, app/user/components/ProfileNovelList.styled.tsx, constants/LIKED_OPTIONS.ts
<br/>
- 선택된 항목 따라 조건부 렌더링
<br/>
<br/>
<br/>
- [fungle #267 ]
<br/>
=> [design] 마이페이지 좋아요 목록 드롭다운 구현 #267

app/api/novel/top10/route.ts, app/user/novel/component/SerialDayBook.tsx, app/user/novel/component/Top10.styled.tsx, app/user/novel/component/Top10.tsx, app/user/novel/page.tsx, application/usecases/novel/DfTopNovelsUsecase.ts, application/usecases/novel/dto/TopList.ts, constants/GENRES.ts, domain/repositories/NovelEpisodeRepository.ts, domain/repositories/NovelRepository.ts, infrastructure/config/novelDi.ts, infrastructure/repositories/PrNovelEpisodeRepository.ts, infrastructure/repositories/PrNovelRepostiory.ts
<br/>
좋아요 + 각 회차당 좋아요 순으로 정렬
<br/>
<br/>
<br/>
- [fungle #263 ]
<br/>
=> [Feat] 소설 메인페이지 top10

app/user/novel/component/MyBook.styled.tsx, app/user/novel/create/page.tsx, application/usecases/novel/dto/NovelsByUserId.ts
<br/>
<br/>
<br/>
https://github.com/user-attachments/assets/f87b8d67-7b89-4430-b4c3-df7fca49a4f7
<br/>
- [fungle #283 ]
<br/>
=> [fix] 연재중인 소설이 있다면 소설 생성 금지

app/api/user/community/liked/route.ts, app/api/user/novel/liked/route.ts, app/user/components/LikedNovelList.tsx, app/user/components/LikedPostList.tsx, application/usecases/auth/DfRefreshTokenUsecase.ts, application/usecases/community/DfLikedCommunityPostsUsecase.ts, application/usecases/novel/DfLikedNovelsUsecase.ts, application/usecases/novel/dto/LikedNovel.ts, domain/repositories/CommunityPostLikeRepository.ts, domain/repositories/NoveLikeRepository.ts, infrastructure/repositories/PrCommunityPostLikeRepository.ts, infrastructure/repositories/PrNovelLikeRepository.ts
<br/>
- 커뮤니티 게시글에 좋아요 누른 목록 조회
- 소설에 좋아요 누른 목록 조회
<br/>
<br/>
<br/>
- [fungle #278]
<br/>
=> [feat] 좋아요 누른 목록 조회 #278

app/api/community/comment/[id]/route.ts, app/user/community/[id]/page.tsx, app/user/community/components/CommunityCommentEdit.tsx, application/usecases/comment/DfCommentCreateUsecase.ts, components/comment/Comment.styled.tsx, components/comment/Comment.tsx, components/comment/CommentCreateTextarea.tsx, components/comment/CommentHeader.tsx, components/comment/ReplyComment.styled.tsx, components/comment/ReplyComment.tsx, domain/repositories/CommunityCommentRepository.ts, infrastructure/repositories/PrCommunityCommentRepository.ts, public/icon/top_arrow.svg
<br/>
- 커뮤니티 대댓글 기능구현
-답글 작성 기능 구현
- 답글 수정 기능 구현
- 답글 삭제 기능 구현
- 답글 작성 시 해당 게시글 작성자면 작성자 UI 추가
- 답글 작성 사용자면 `MoreOptions` 버튼 활성화 
<br/>
https://github.com/user-attachments/assets/77d1136c-278f-4e64-8ef6-8756ae62d7ac
<br/>
<b#274 
- [fungle #274]
<br/>
=> [feat] 커뮤니티 대댓글 기능 구현 #274

infrastructure/repositories/PrNovelRepostiory.ts
=> [hotfix] 03/09 novel repository 괄호 추가 #293

application/usecases/novel/DfNovelUsecase.ts
=> [fix] author, profile null일때 예외처리 #297

app/user/novel/create/page.tsx, application/usecases/novel/dto/OngoingNovel.ts
<br/>
<br/>
<br/>
<br/>
- [fungle #292 ]
<br/>
=> [feat] 연재중인 소설 있으면 연재 페이지로 리다이렉트

app/user/novel/component/MyBook.styled.tsx, app/user/novel/component/SerialDayBook.styled.tsx, app/user/novel/component/Top10.styled.tsx
<br/>
<br/>
<br/>
<br/>
- [fungle #301 ]
<br/>
=> [design] 메인페이지 소설 제목, 이미지 크기 고정 

app/user/novel/[novelId]/(episode)/[episodeId]/page.tsx, app/user/novel/component/Top10.styled.tsx, app/user/novel/component/Top10.tsx
<br/>
<br/>
<br/>
<br/>
- [fungle #308 ]
<br/>
=> [fix] top 10 리스트 요소 클릭 가능

prisma/schema.prisma
<br/>
-  NovelComment 테이블 parentId 추가
- 대댓글을 위한 컬럼 추가
<br/>
<br/>
<br/>
- [fungle #313 ]
<br/>
=> [database] NovelComment 테이블 parentId 추가 #313

components/header/Header.styled.tsx, components/header/Header.tsx
<br/>
- 로그아웃 할 때 zustand로 관리하는 사용자 정보 null로 변경
<br/>
<br/>
<br/>
- [fungle #298 ]
<br/>
=> [feat] 로그아웃 시 zustand로 관리하는 사용자 정보 변경 #298

app/(main)/user/community/[id]/loading.tsx, application/usecases/comment/DfCommentCountUsecase.ts
<br/>
- 커뮤니티 상세 페이지 진입 시 데이터를 불러오기 전 보여질 Loading UI 작업
<br/>
<br/>
<br/>
- [fungle #323 ]
<br/>
=> [design] 커뮤니티 Loading 컴포넌트 작업 #323 

app/(main)/layout.tsx, app/admin/AdminPage.styled.tsx, app/admin/layout.tsx, app/admin/novel/AdminNovelPage.styled.tsx, app/admin/novel/components/ApproveButton.tsx, app/admin/novel/components/RejectionButton.tsx, app/admin/novel/page.tsx, app/api/admin/novel-episode/[episodeId]/route.ts, app/api/admin/novel-episode/route.ts, app/layout.tsx, application/usecases/novel/DfDeleteNovelEpisodeUsecase.ts, application/usecases/novel/DfNovelEpisodeWithUserInfoUsecase.ts, application/usecases/novel/DfUpdateNovelEpisodeStatusUsecase.ts, application/usecases/novel/dto/EpisodeWithUserInfo.ts, application/usecases/novel/dto/NovelEpisodeWithUserInfo.ts, domain/repositories/NovelEpisodeRepository.ts, infrastructure/repositories/PrNovelEpisodeRepository.ts, store/useAdminNovelStore.ts
<br/>
- 관리자 소설 검토 페이지 구현
- 등록 거절 시 삭제
- 검토 완료 시 에피소드 status: approved
- isLastEpisode가 true이면 serialStatus: completed로 변경
<br/>
<br/>
<br/>
- [fungle #319]
<br/>
=> [feat] 관리자 소설 검토 구현 #319

components/header/Header.tsx
<br/>
-안 쓰는 useEffect 삭제 
<br/>
<br/>
- 안 쓰는 코드 삭제 
<br/>
- [fungle #347 ]
<br/>
=> [fix] 03/11 안 쓰는 코드 삭제

app/(main)/(anon)/signup/components/NicknameValidation.tsx, app/api/auth/verify-code/route.ts, application/usecases/auth/DfSendEmailUsecase.ts
<br/>
- 인증 코드 콘솔 출력 코드 삭제 
- 에러 코드 추가 
<br/>
<br/>
- 펀딩 페이지 작업
<br/>
- [fungle#347]
<br/>
=> [fix] 회원가입 빌드 에러 수정

app/(main)/(anon)/login/LoginPage.styled.tsx, app/(main)/(anon)/login/actions/loginProc.ts, app/(main)/(anon)/login/page.tsx, app/(main)/(anon)/page.styled.tsx, app/(main)/(anon)/page.tsx, app/(main)/user/components/LikedNovelList.tsx, app/(main)/user/components/LikedPostList.tsx, app/(main)/user/components/PostAndLikedListWrapper.styled.tsx, app/(main)/user/components/ProfileInfo.tsx, app/(main)/user/components/ProfileIntroduce.tsx, app/(main)/user/components/ProfileNovelList.tsx, app/(main)/user/components/ProfilePostList.tsx, app/(main)/user/components/ProfileView.tsx, app/admin/novel/page.tsx, app/api/auth/verify/route.ts, app/api/user/community/liked/route.ts, app/api/user/community/route.ts, app/api/user/count/route.ts, app/api/user/delete/route.ts, app/api/user/introduce/route.ts, app/api/user/nickname/route.ts, app/api/user/novel/liked/route.ts, app/api/user/novel/route.ts, app/api/user/profile-image/route.ts, components/authInitializer/AuthInitializer.tsx, components/textarea/Textarea.tsx
<br/>
빌드 오류 수정
<br/>
<br/>
<br/>
- [fungle #343 ]
<br/>
=> [fix] 03/11 빌드 오류 수정 #343

app/(main)/user/novel/component/comments/NovelComment.tsx, app/(main)/user/novel/component/comments/NovelReplyComment.tsx, components/comment/Comment.styled.tsx, components/comment/Comment.tsx, components/comment/ReplyComment.styled.tsx, components/comment/ReplyComment.tsx
<br/>
- autor -> author 오타 수정
<br/>
<br/>
<br/>
<br/>
=> [refactor] 03/11 autor -> author 오타 수정 #353

app/(main)/user/funding/page.tsx
<br/>
<br/>
<br/>
<br/>
- [fungle #358 ]
<br/>
=> [design] 빌드 에러 수정

app/(main)/user/funding/page.tsx, package.json
=> [fix] 펀딩 빌드 에러 해결 

app/(main)/(anon)/login/actions/loginProc.ts, app/(main)/(anon)/login/page.tsx, app/(main)/user/novel/component/SerialDayBook.tsx, app/api/community/[id]/route.ts, app/api/community/comment/[id]/route.ts, app/api/novel/[novelId]/route.ts, app/api/novel/serial-day/[day]/route.ts, middleware.ts, utils/params/requestParams.ts
<br/>
- 파라미터 오류 수정
- 미들웨어 수정
- redirectUrl 수정
<br/>
<br/>
<br/>
- [fungle #357 ]
<br/>
=> [fix] 03/12 파라미터 오류 수정 #357

app/api/logout/route.ts, application/usecases/auth/DfRefreshTokenUsecase.ts
<br/>
로그아웃시 쿠키에 lastUserId 남아있는 문제 해결
<br/>
<br/>
<br/>
- [fungle #357 ]
<br/>
=> [fix] 로그아웃 시 사용자 아이디 삭제 #357

package.json
<br/>
- package.json port 제거
<br/>
<br/>
<br/>
<br/>
=> [setting] package.json port 제거 #370

package.json
<br/>
- build중에 prisma 설정하기 
<br/>
<br/>
<br/>
<br/>
=> [fix] 03/12 build 중에 prisma 설정

components/authInitializer/AuthInitializer.tsx
<br/>
사용자 검증 경로 수정 
<br/>
<br/>
<br/>
- [fungle #375]
<br/>
=> [fix] 사용자 검증 경로 수정 #375

components/authInitializer/AuthInitializer.tsx, package.json
<br/>
develop -> main 배포 merge
<br/>
<br/>
<br/>
<br/>
=> [merge] develop -> main 배포 merge

app/api/novel/[novelId]/[episodeId]/comments/[id]/like/route.ts, app/api/novel/[novelId]/[episodeId]/comments/[id]/route.ts, app/api/novel/[novelId]/[episodeId]/comments/route.ts
<br/>
<br/>
<br/>
<br/>
- [fungle #357 ]
<br/>
=> [fix] 소설 파라미터 수정 #357

app/(main)/user/novel/[novelId]/(episode)/[episodeId]/EpisodePage.styled.tsx, app/(main)/user/novel/[novelId]/NovelIdPage.styled.tsx
=> [fix] 소설 개행 

app/(main)/user/novel/[novelId]/(episode)/[episodeId]/EpisodePage.styled.tsx, app/(main)/user/novel/[novelId]/NovelIdPage.styled.tsx
Reverts FRONT-END-BOOTCAMP-PLUS-3/fungle#384
=> Revert "[fix] 소설 개행 "

app/(main)/user/novel/[novelId]/(episode)/[episodeId]/EpisodePage.styled.tsx, app/(main)/user/novel/[novelId]/NovelIdPage.styled.tsx
=> [fix] 03/13 소설 개행 #383

app/(main)/(anon)/funding/fail/page.tsx
<br/>
- 배포를 위한 funding 실패 페이지 기본 구성
<br/>
<br/>
<br/>
- [fungle #392 ]
<br/>
=> [design] 펀딩 실패 페이지 UI #392

app/(main)/(anon)/funding/fail/page.tsx, app/(main)/(anon)/funding/success/page.tsx, app/(main)/user/funding/components/FundingCompleted.tsx
<br/>
- 펀딩 빌드 오류 해결
<br/>
<br/>
<br/>
<br/>
=> [fix] 03/13 펀딩 빌드 오류 해결

app/(main)/user/novel/[novelId]/(episode)/[episodeId]/EpisodePage.styled.tsx, app/(main)/user/novel/[novelId]/NovelIdPage.styled.tsx, app/(main)/user/novel/component/SearchBook.styled.tsx
<br/>
<br/>
<br/>
<br/>
- [fungle #383 ]
<br/>
=> [design] 03/14 소설 css 수정 #383

app/(main)/user/community/components/CommunitySearchFilter.tsx
<br/>
- community filter input 사이즈 수정
<br/>
<br/>
<br/>
- [fungle #401 ]
<br/>
=> [!hotfix]  community filter input 사이즈 수정 #401

app/(main)/user/novel/component/Top10.styled.tsx
<br/>
<br/>
<br/>
<br/>
- [fungle #405 ]
<br/>
=> [design] 03/17 top 10 리스트 어긋남 ui 수정 #405
